Debug (#289)
Prep for release

diff --git a/.github/workflows/eventbuild.yml b/.github/workflows/eventbuild.yml
--- a/.github/workflows/eventbuild.yml
+++ b/.github/workflows/eventbuild.yml
@@ -6,7 +6,6 @@ on:
       - "2.5-evo"
       - "dev-release"
       - "release"
-      - "debug"
 jobs:
   build:
 
@@ -15,7 +14,8 @@ jobs:
       fail-fast: false # Don't fail all if any of the jobs is failing
       matrix:
         TARGET: [pi-bullseye, x86-lunar, radxa-cm3, x20, radxa-zero3w] # <-- Add targets here!
-        #TARGET: [x20,radxa-zero3w] # <-- Add targets here!
+< debug
+        #TARGET: [radxa-cm3] # <-- Add targets here!
     steps:
     - name: Maximize build space
       uses: easimon/maximize-build-space@master
@@ -68,7 +68,10 @@ jobs:
           make
           sudo make install
     - name: configure
-      run: sudo ./build.sh ${{ matrix.TARGET }}
+      run: |
+        touch additionalFiles/issue-new.txt
+        echo "OpenHD-image-${{ matrix.TARGET }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}" > additionalFiles/issue-new.txt
+        sudo ./build.sh ${{ matrix.TARGET }}
     # - name: debug
     #   run: |
     #     dd if=/dev/zero of=large_image.img bs=1M count=5650
@@ -113,107 +116,108 @@ jobs:
           *.img
           if-no-files-found: error
 
-  createEmmcImage:
-    needs: build
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false # Don't fail all if any of the jobs is failing
-      matrix:
-        TARGET: [radxa-zero3w] # <-- Add targets here!
+  # createEmmcImage:
+  #   needs: build
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false # Don't fail all if any of the jobs is failing
+  #     matrix:
+  #       TARGET: [radxa-cm3] # <-- Add targets here!
         
-    steps:
-    - name: Maximize build space
-      uses: easimon/maximize-build-space@master
-      with:
-        root-reserve-mb: 100
-        swap-size-mb: 200
-        remove-dotnet: 'true'
-        remove-android: 'true'
-        remove-haskell: 'true'
-        remove-codeql: 'true'
-        remove-docker-images: 'true'
-        overprovision-lvm: 'true'
+  #   steps:
+  #   - name: Maximize build space
+  #     uses: easimon/maximize-build-space@master
+  #     with:
+  #       root-reserve-mb: 100
+  #       swap-size-mb: 200
+  #       remove-dotnet: 'true'
+  #       remove-android: 'true'
+  #       remove-haskell: 'true'
+  #       remove-codeql: 'true'
+  #       remove-docker-images: 'true'
+  #       overprovision-lvm: 'true'
 
-    - name: Setup env
-      run: |
-        echo "DT=$(date -d '+1 hour' +'%m-%d-%Y--%H-%M-%S')" >> $GITHUB_ENV
-        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
+  #   - name: Setup env
+  #     run: |
+  #       echo "DT=$(date -d '+1 hour' +'%m-%d-%Y--%H-%M-%S')" >> $GITHUB_ENV
+  #       echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
 
-        if [ "${{ matrix.TARGET }}" == "radxa-zero3w" ]; then
-          ARTIFACT_PREFIX="zero3w"
-        elif [ "${{ matrix.TARGET }}" == "radxa-cm3" ]; then
-          ARTIFACT_PREFIX="34te"
-        elif [ "${{ matrix.TARGET }}" == "radxa-cm5" ]; then
-          ARTIFACT_PREFIX="radxa-323"
-        else
-          echo "Unsupported TARGET"
-          exit 1
-        fi
-        echo "ARTIFACT_PREFIX=${ARTIFACT_PREFIX}" >> $GITHUB_ENV
+  #       if [ "${{ matrix.TARGET }}" == "radxa-zero3w" ]; then
+  #         ARTIFACT_PREFIX="zero3w"
+  #       elif [ "${{ matrix.TARGET }}" == "radxa-cm3" ]; then
+  #         ARTIFACT_PREFIX="34te"
+  #       elif [ "${{ matrix.TARGET }}" == "radxa-cm5" ]; then
+  #         ARTIFACT_PREFIX="radxa-323"
+  #       else
+  #         echo "Unsupported TARGET"
+  #         exit 1
+  #       fi
+  #       echo "ARTIFACT_PREFIX=${ARTIFACT_PREFIX}" >> $GITHUB_ENV
       
-    - name: Checkout
-      uses: actions/checkout@v3
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
         
-    - name: dep
-      run: sudo apt update && sudo apt-get install -y unzip curl git qemu qemu-user-static binfmt-support
+  #   - name: dep
+  #     run: sudo apt update && sudo apt-get install -y unzip curl git qemu qemu-user-static binfmt-support
 
-    - name: List Artifacts
-      id: list_artifacts
-      run: |
-        artifacts=$(curl -s -X GET \
-          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")
+  #   - name: List Artifacts
+  #     id: list_artifacts
+  #     run: |
+  #       artifacts=$(curl -s -X GET \
+  #         -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+  #         "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")
 
-        artifacts_filtered=$(echo "$artifacts" | jq -r '.artifacts[] | select(.name | startswith(env.ARTIFACT_PREFIX)) | .name')
+  #       artifacts_filtered=$(echo "$artifacts" | jq -r '.artifacts[] | select(.name | startswith(env.ARTIFACT_PREFIX)) | .name')
 
-        echo "::set-output name=artifacts_filtered::$artifacts_filtered"
+  #       echo "::set-output name=artifacts_filtered::$artifacts_filtered"
 
-    - name: Print Artifacts
-      run: |
-        echo "Artifacts: ${{ steps.list_artifacts.outputs.artifacts_filtered }}"
-
-    - name: Download Zero3w Artifact
-      id: download_zero3w_artifact
-      uses: actions/download-artifact@v3
-      with:
-        name: ${{ steps.list_artifacts.outputs.zero3w_artifacts }}
+  #   - name: Print Artifacts
+  #     run: |
+  #       echo "Artifacts: ${{ steps.list_artifacts.outputs.artifacts_filtered }}"
 
 
-    - name: debug_step
-      run: |
-        mkdir -p additionalFiles
-        touch emmc
-        touch additionalFiles/emmc
-        ls -a
+  #   - name: Download Zero3w Artifact
+  #     id: download_zero3w_artifact
+  #     uses: actions/download-artifact@v3
+  #     with:
+  #       name: ${{ steps.list_artifacts.outputs.zero3w_artifacts }}
+
+
+  #   - name: debug_step
+  #     run: |
+  #       mkdir -p additionalFiles
+  #       touch emmc
+  #       touch additionalFiles/emmc
+  #       ls -a
     
-    - name: buildImage
-      run: |
-        ls -a
-        sudo apt install -y xz-utils
-        cd radxa-zero3w-*
-        ls -a
-        cp *.img ../additionalFiles/emmc.img
-        cd ../additionalFiles
-        gzip -c *.img > emmc.img.gz
-        rm *.img
-        cd ../
-        ls -a
-        sudo ./build.sh ${{ matrix.TARGET }}
-        cd deploy
-        sudo mv *.img ../OpenHD-EMMC-${{ matrix.TARGET }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}.img
+  #   - name: buildImage
+  #     run: |
+  #       ls -a
+  #       sudo apt install -y xz-utils
+  #       cd radxa-*
+  #       ls -a
+  #       cp *.img ../additionalFiles/emmc.img
+  #       cd ../additionalFiles
+  #       gzip -c *.img > emmc.img.gz
+  #       rm *.img
+  #       cd ../
+  #       ls -a
+  #       sudo ./build.sh ${{ matrix.TARGET }}
+  #       cd deploy
+  #       sudo mv *.img ../OpenHD-EMMC-${{ matrix.TARGET }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}.img
 
     
-    - name: Compose release filename
-      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
-      run: echo "artifact_name=OpenHD-EMMC-image-${{ matrix.TARGET }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}" >> $GITHUB_ENV
+  #   - name: Compose release filename
+  #     # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
+  #     run: echo "artifact_name=OpenHD-EMMC-image-${{ matrix.TARGET }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}" >> $GITHUB_ENV
         
-    - name: Pack image for ${{ matrix.TARGET }}
-      uses: 'actions/upload-artifact@v3'
-      with:
-        name: "${{ matrix.TARGET }}-${{ env.DT }}-EMMC"
-        path: |
-          *.img
-          if-no-files-found: error
+  #   - name: Pack image for ${{ matrix.TARGET }}
+  #     uses: 'actions/upload-artifact@v3'
+  #     with:
+  #       name: "${{ matrix.TARGET }}-${{ env.DT }}-EMMC"
+  #       path: |
+  #         *.img
+  #         if-no-files-found: error
 
   upload:
     if: "github.event_name == 'push' && github.ref == 'refs/heads/release'"
@@ -292,78 +296,78 @@ jobs:
         aws s3 --endpoint-url $aws_endpoint cp ${{ matrix.TARGET }}.txt s3://$aws_s3_bucket/Downloader/temp/${{ matrix.TARGET }}.txt
 
 
-  upload2:
-    if: "github.event_name == 'push' && github.ref == 'refs/heads/release'"
-    needs: createEmmcImage
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false # Don't fail all if any of the jobs is failing
-      matrix:
-        TARGET: [radxa-zero3w] # <-- Add targets here!
-    steps:
-    - name: debug
-      run: df -h
+  # upload2:
+  #   if: "github.event_name == 'push' && github.ref == 'refs/heads/release'"
+  #   needs: createEmmcImage
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false # Don't fail all if any of the jobs is failing
+  #     matrix:
+  #       TARGET: [radxa-zero3w] # <-- Add targets here!
+  #   steps:
+  #   - name: debug
+  #     run: df -h
 
-    - uses: actions/checkout@v3
+  #   - uses: actions/checkout@v3
 
-    - uses: actions/download-artifact@v3
-      with:
-        name: "${{ matrix.TARGET }}-${{ env.DT }}"
+  #   - uses: actions/download-artifact@v3
+  #     with:
+  #       name: "${{ matrix.TARGET }}-${{ env.DT }}"
     
-    - name: compress
-      run: |
-        mkdir OpenHD
-        mv *.img OpenHD
-        cd OpenHD*
-        rm -Rf OpenHD-image-radxa-zero3w*
-        sha256sum * | cut -f 1 -d " " > ../sha256
-        echo 'NAME<<EOF' >> $GITHUB_ENV
-        ls -1 | sed -e 's/.img/.img.xz/g' >> $GITHUB_ENV
-        echo 'EOF' >> $GITHUB_ENV
-        echo 'SIZEFULL<<EOF' >> $GITHUB_ENV
-        wc -c *.img | cut -f 1 -d " " >> $GITHUB_ENV
-        echo 'EOF' >> $GITHUB_ENV
-        xz -v7T0 *.img
-        mv * ../
+  #   - name: compress
+  #     run: |
+  #       mkdir OpenHD
+  #       mv *.img OpenHD
+  #       cd OpenHD*
+  #       rm -Rf OpenHD-image-radxa-zero3w*
+  #       sha256sum * | cut -f 1 -d " " > ../sha256
+  #       echo 'NAME<<EOF' >> $GITHUB_ENV
+  #       ls -1 | sed -e 's/.img/.img.xz/g' >> $GITHUB_ENV
+  #       echo 'EOF' >> $GITHUB_ENV
+  #       echo 'SIZEFULL<<EOF' >> $GITHUB_ENV
+  #       wc -c *.img | cut -f 1 -d " " >> $GITHUB_ENV
+  #       echo 'EOF' >> $GITHUB_ENV
+  #       xz -v7T0 *.img
+  #       mv * ../
 
-    - name: Upload to R2
-      shell: bash
-      env:
-        aws_endpoint: "https://fra1.digitaloceanspaces.com"
-        aws_key_id: ${{ secrets.DIGITALOCEAN_ACCESS_KEY_ID }}
-        aws_secret_access_key: ${{ secrets.DIGITALOCEAN_SECRET_ACCESS_KEY }}
-        aws_s3_bucket: openhd-images
-        AWS_EC2_METADATA_DISABLED: true
-      run: |
-        aws configure set aws_access_key_id $aws_key_id
-        aws configure set aws_secret_access_key $aws_secret_access_key 
-        aws s3 --endpoint-url $aws_endpoint cp ${{ env.NAME }} s3://$aws_s3_bucket/Downloader/temp/${{ env.NAME }}
+  #   - name: Upload to R2
+  #     shell: bash
+  #     env:
+  #       aws_endpoint: "https://fra1.digitaloceanspaces.com"
+  #       aws_key_id: ${{ secrets.DIGITALOCEAN_ACCESS_KEY_ID }}
+  #       aws_secret_access_key: ${{ secrets.DIGITALOCEAN_SECRET_ACCESS_KEY }}
+  #       aws_s3_bucket: openhd-images
+  #       AWS_EC2_METADATA_DISABLED: true
+  #     run: |
+  #       aws configure set aws_access_key_id $aws_key_id
+  #       aws configure set aws_secret_access_key $aws_secret_access_key 
+  #       aws s3 --endpoint-url $aws_endpoint cp ${{ env.NAME }} s3://$aws_s3_bucket/Downloader/temp/${{ env.NAME }}
 
-    - name: generate variables for the ImageWriter
-      run: |
-        export NAME=$(cat last.release)
-        export FILESIZE=${{ env.SIZEFULL }}
-        export FILENAME=${{ env.NAME }}
-        export DOWNLOADSIZE=$(wc -c *.xz | cut -f 1 -d " ")
-        export SUM=$(cat sha256)
-        export RELEASEDATE=$(date -d '+1 hour' +'%m-%d-%Y--%H-%M-%S')
-        echo "$NAME" >> ${{ matrix.TARGET }}.txt
-        echo "$FILESIZE" >> ${{ matrix.TARGET }}.txt
-        echo "$FILENAME" >> ${{ matrix.TARGET }}.txt
-        echo "$DOWNLOADSIZE" >> ${{ matrix.TARGET }}.txt
-        echo "$SUM" >> ${{ matrix.TARGET }}.txt
-        echo "$RELEASEDATE" >> ${{ matrix.TARGET }}.txt
-        wc -c *.xz | cut -f 1 -d " "
+  #   - name: generate variables for the ImageWriter
+  #     run: |
+  #       export NAME=$(cat last.release)
+  #       export FILESIZE=${{ env.SIZEFULL }}
+  #       export FILENAME=${{ env.NAME }}
+  #       export DOWNLOADSIZE=$(wc -c *.xz | cut -f 1 -d " ")
+  #       export SUM=$(cat sha256)
+  #       export RELEASEDATE=$(date -d '+1 hour' +'%m-%d-%Y--%H-%M-%S')
+  #       echo "$NAME" >> ${{ matrix.TARGET }}.txt
+  #       echo "$FILESIZE" >> ${{ matrix.TARGET }}.txt
+  #       echo "$FILENAME" >> ${{ matrix.TARGET }}.txt
+  #       echo "$DOWNLOADSIZE" >> ${{ matrix.TARGET }}.txt
+  #       echo "$SUM" >> ${{ matrix.TARGET }}.txt
+  #       echo "$RELEASEDATE" >> ${{ matrix.TARGET }}.txt
+  #       wc -c *.xz | cut -f 1 -d " "
 
-    - name: Upload text-files
-      shell: bash
-      env:
-        aws_endpoint: "https://fra1.digitaloceanspaces.com"
-        aws_key_id: ${{ secrets.DIGITALOCEAN_ACCESS_KEY_ID }}
-        aws_secret_access_key: ${{ secrets.DIGITALOCEAN_SECRET_ACCESS_KEY }}
-        aws_s3_bucket: openhd-images
-        AWS_EC2_METADATA_DISABLED: true
-      run: |
-        aws configure set aws_access_key_id $aws_key_id
-        aws configure set aws_secret_access_key $aws_secret_access_key 
-        aws s3 --endpoint-url $aws_endpoint cp ${{ matrix.TARGET }}.txt s3://$aws_s3_bucket/Downloader/temp/${{ matrix.TARGET }}.txt
+  #   - name: Upload text-files
+  #     shell: bash
+  #     env:
+  #       aws_endpoint: "https://fra1.digitaloceanspaces.com"
+  #       aws_key_id: ${{ secrets.DIGITALOCEAN_ACCESS_KEY_ID }}
+  #       aws_secret_access_key: ${{ secrets.DIGITALOCEAN_SECRET_ACCESS_KEY }}
+  #       aws_s3_bucket: openhd-images
+  #       AWS_EC2_METADATA_DISABLED: true
+  #     run: |
+  #       aws configure set aws_access_key_id $aws_key_id
+  #       aws configure set aws_secret_access_key $aws_secret_access_key 
+  #       aws s3 --endpoint-url $aws_endpoint cp ${{ matrix.TARGET }}.txt s3://$aws_s3_bucket/Downloader/temp/${{ matrix.TARGET }}.txt
